### ISSUE TITLE
600比700还粗

### ISSUE THREAD

**Issue by mengyangzhi** [simplepeng/FontWeightTextView#2]
在真机上600比700还粗噢

**Comment by simplepeng** [comment]
@mengyangzhi 哪款机型呢，什么系统。都是调用Androidx提供的方法，有问题应该要么就是Google的锅，要么就是国内厂商的锅😂

**Comment by mengyangzhi** [comment]
..还真是  我在小米10pro上看600比700大  在华为上mate40上看是正常的
